// Writing style types - First principles: Keep it simple, learn automatically

export type WritingStylePreset = 
  | 'literary'      // Sophisticated, introspective
  | 'commercial'    // Accessible, engaging
  | 'experimental'  // Unconventional, artistic
  | 'custom';       // User's own style (learned)

export interface WritingStyle {
  id?: string;             // Unique ID for style profile
  name?: string;           // User-defined name (e.g., "My Mystery Style")
  preset?: WritingStylePreset;
  customTraits?: string[]; // Auto-extracted traits from user's writing
  learnedFrom?: string;    // Sample text used for learning
  updatedAt: number;
  generatedBy?: 'LLM' | 'local'; // Whether style was generated by LLM or local analysis
  // Multi-document learning support
  learningSamples?: Array<{
    text: string;
    analyzedAt: number;
    traits: string[];
  }>;
  confidence?: number;     // Style match confidence (0-1)
  // User adjustments
  adjustments?: {
    toneAdjustment?: number;      // -1 to 1
    pacingAdjustment?: number;    // -1 to 1
    sentenceLengthAdjustment?: number; // -1 to 1
    vocabularyAdjustment?: number;     // -1 to 1
  };
}

// Style analysis result
export interface StyleAnalysis {
  tone: 'formal' | 'casual' | 'poetic' | 'conversational' | 'neutral';
  pacing: 'fast' | 'moderate' | 'slow';
  perspective: 'first-person' | 'third-person' | 'mixed';
  sentenceLength: 'short' | 'medium' | 'long';
  vocabulary: 'simple' | 'moderate' | 'complex';
}

// Scene types for contextual style application
export type SceneType = 
  | 'action'       // Action scenes: fast-paced, dynamic
  | 'emotional'    // Emotional scenes: slow, introspective
  | 'dialogue'     // Dialogue scenes: character-driven
  | 'descriptive'  // Descriptive scenes: detailed, immersive
  | 'reflective'   // Reflective scenes: contemplative, philosophical
  | 'mixed';       // Mixed or unclear scene type

// Contextual style adjustment
export interface ContextualStyleAdjustment {
  scene: SceneType;
  pacingAdjustment?: 'faster' | 'slower' | 'maintain';
  sentenceLengthAdjustment?: 'shorter' | 'longer' | 'maintain';
  toneAdjustment?: 'more-intense' | 'more-subtle' | 'maintain';
}


